# https://travis-ci.org/jwtk/jjwt

#sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk10
  - openjdk11
  - openjdk14

cache:
  directories:
    - $HOME/.m2

before_install:
  - echo "TRAVIS_JDK_VERSION is ${TRAVIS_JDK_VERSION}"
  - export MVN_CMD="./mvnw --no-transfer-progress" # hide verbose download messages (log spam)
  # If on JDK 8, ensure build coverage assertions are run (we only need to run this on one JDK to reduce overall build times):
  - export BUILD_COVERAGE="$([ $TRAVIS_JDK_VERSION == 'oraclejdk8' ] && echo 'true')"

# prints the Maven, Java, and OS info/version
install: $MVN_CMD --version

script:
  - $MVN_CMD install
  - test -z "$BUILD_COVERAGE" || { $MVN_CMD clean clover:setup test && $MVN_CMD -pl . clover:clover clover:check coveralls:report; }
